# Generated by Django 3.1.1 on 2020-09-05 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyitemrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surveyitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='survey.surveyitem'),
        ),
        migrations.AddField(
            model_name='surveyitem',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question'),
        ),
        migrations.AddField(
            model_name='surveyitem',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey'),
        ),
        migrations.AlterUniqueTogether(
            name='survey',
            unique_together={('name', 'version')},
        ),
        migrations.AddField(
            model_name='question',
            name='catageory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.catageory'),
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='survey.answertype', verbose_name='AnswerType'),
        ),
        migrations.AddField(
            model_name='question',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='survey.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ManyToManyField(through='survey.SurveyItem', to='survey.Survey'),
        ),
        migrations.CreateModel(
            name='BooleanAnswer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('survey.answertype',),
        ),
        migrations.CreateModel(
            name='IntAnswer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('survey.answertype',),
        ),
        migrations.CreateModel(
            name='MultipleChoiceAnswer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('survey.answertype',),
        ),
        migrations.CreateModel(
            name='NumberRangeAnswer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('survey.answertype',),
        ),
        migrations.AlterUniqueTogether(
            name='surveyitemrecord',
            unique_together={('user', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='surveyitem',
            unique_together={('question', 'survey')},
        ),
        migrations.CreateModel(
            name='ZipCodeAnswer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('survey.intanswer',),
        ),
    ]
